### ISSUE TITLE
selected upper-left, but generator makes Y twice the size.

### ISSUE THREAD

**Issue by ghost** [neilferreri/gCode-Generator#1]
Tool Diameter (mm or in): 8
Stock Size X (mm or in): 312.5
Stock Size Y (mm or in): 185
Feedrate (mm/min or in/min): 2000
Spindle Speed (RPM): 1000
Depth of Cut / Depth per Pass (mm or in): 0.25
Maximum Depth (mm or in): 0.5
Toolpath Direction: along X
XY Zero Point: Upper Left
Cutting Direction: Both
Stepover Percentage: 40
Safe Retract Height (mm or in): 1

G90
G21
G0 Z1.000
M3 S12000
G0 Z1.000
G0 X0.000 Y-185.000
G1 Z-0.250 F2000
G1 X312.500 F2000
G1 Y-181.800
G1 X0.000F2000
G0 Y-178.600
G1 X312.500 F2000
G1 Y-175.400
G1 X0.000F2000
G0 Y-172.200
G1 X312.500 F2000
G1 Y-169.000
G1 X0.000F2000
G0 Y-165.800
G1 X312.500 F2000
G1 Y-162.600
G1 X0.000F2000
G0 Y-159.400
G1 X312.500 F2000
G1 Y-156.200
G1 X0.000F2000
G0 Y-153.000
G1 X312.500 F2000
G1 Y-149.800
G1 X0.000F2000
G0 Y-146.600
G1 X312.500 F2000
G1 Y-143.400
G1 X0.000F2000
G0 Y-140.200
G1 X312.500 F2000
G1 Y-137.000
G1 X0.000F2000
G0 Y-133.800
G1 X312.500 F2000
G1 Y-130.600
G1 X0.000F2000
G0 Y-127.400
G1 X312.500 F2000
G1 Y-124.200
G1 X0.000F2000
G0 Y-121.000
G1 X312.500 F2000
G1 Y-117.800
G1 X0.000F2000
G0 Y-114.600
G1 X312.500 F2000
G1 Y-111.400
G1 X0.000F2000
G0 Y-108.200
G1 X312.500 F2000
G1 Y-105.000
G1 X0.000F2000
G0 Y-101.800
G1 X312.500 F2000
G1 Y-98.600
G1 X0.000F2000
G0 Y-95.400
G1 X312.500 F2000
G1 Y-92.200
G1 X0.000F2000
G0 Y-89.000
G1 X312.500 F2000
G1 Y-85.800
G1 X0.000F2000
G0 Y-82.600
G1 X312.500 F2000
G1 Y-79.400
G1 X0.000F2000
G0 Y-76.200
G1 X312.500 F2000
G1 Y-73.000
G1 X0.000F2000
G0 Y-69.800
G1 X312.500 F2000
G1 Y-66.600
G1 X0.000F2000
G0 Y-63.400
G1 X312.500 F2000
G1 Y-60.200
G1 X0.000F2000
G0 Y-57.000
G1 X312.500 F2000
G1 Y-53.800
G1 X0.000F2000
G0 Y-50.600
G1 X312.500 F2000
G1 Y-47.400
G1 X0.000F2000
G0 Y-44.200
G1 X312.500 F2000
G1 Y-41.000
G1 X0.000F2000
G0 Y-37.800
G1 X312.500 F2000
G1 Y-34.600
G1 X0.000F2000
G0 Y-31.400
G1 X312.500 F2000
G1 Y-28.200
G1 X0.000F2000
G0 Y-25.000
G1 X312.500 F2000
G1 Y-21.800
G1 X0.000F2000
G0 Y-18.600
G1 X312.500 F2000
G1 Y-15.400
G1 X0.000F2000
G0 Y-12.200
G1 X312.500 F2000
G1 Y-9.000
G1 X0.000F2000
G0 Y-5.800
G1 X312.500 F2000
G1 Y-2.600
G1 X0.000F2000
G0 Y0.600
G1 X312.500 F2000
G1 Y3.800
G1 X0.000F2000
G0 Y7.000
G1 X312.500 F2000
G1 Y10.200
G1 X0.000F2000
G0 Y13.400
G1 X312.500 F2000
G1 Y16.600
G1 X0.000F2000
G0 Y19.800
G1 X312.500 F2000
G1 Y23.000
G1 X0.000F2000
G0 Y26.200
G1 X312.500 F2000
G1 Y29.400
G1 X0.000F2000
G0 Y32.600
G1 X312.500 F2000
G1 Y35.800
G1 X0.000F2000
G0 Y39.000
G1 X312.500 F2000
G1 Y42.200
G1 X0.000F2000
G0 Y45.400
G1 X312.500 F2000
G1 Y48.600
G1 X0.000F2000
G0 Y51.800
G1 X312.500 F2000
G1 Y55.000
G1 X0.000F2000
G0 Y58.200
G1 X312.500 F2000
G1 Y61.400
G1 X0.000F2000
G0 Y64.600
G1 X312.500 F2000
G1 Y67.800
G1 X0.000F2000
G0 Y71.000
G1 X312.500 F2000
G1 Y74.200
G1 X0.000F2000
G0 Y77.400
G1 X312.500 F2000
G1 Y80.600
G1 X0.000F2000
G0 Y83.800
G1 X312.500 F2000
G1 Y87.000
G1 X0.000F2000
G0 Y90.200
G1 X312.500 F2000
G1 Y93.400
G1 X0.000F2000
G0 Y96.600
G1 X312.500 F2000
G1 Y99.800
G1 X0.000F2000
G0 Y103.000
G1 X312.500 F2000
G1 Y106.200
G1 X0.000F2000
G0 Y109.400
G1 X312.500 F2000
G1 Y112.600
G1 X0.000F2000
G0 Y115.800
G1 X312.500 F2000
G1 Y119.000
G1 X0.000F2000
G0 Y122.200
G1 X312.500 F2000
G1 Y125.400
G1 X0.000F2000
G0 Y128.600
G1 X312.500 F2000
G1 Y131.800
G1 X0.000F2000
G0 Y135.000
G1 X312.500 F2000
G1 Y138.200
G1 X0.000F2000
G0 Y141.400
G1 X312.500 F2000
G1 Y144.600
G1 X0.000F2000
G0 Y147.800
G1 X312.500 F2000
G1 Y151.000
G1 X0.000F2000
G0 Y154.200
G1 X312.500 F2000
G1 Y157.400
G1 X0.000F2000
G0 Y160.600
G1 X312.500 F2000
G1 Y163.800
G1 X0.000F2000
G0 Y167.000
G1 X312.500 F2000
G1 Y170.200
G1 X0.000F2000
G0 Y173.400
G1 X312.500 F2000
G1 Y176.600
G1 X0.000F2000
G0 Y179.800
G1 X312.500 F2000
G1 Y183.000
G1 X0.000F2000
G0 Z1.000
G0 X0.000 Y-185.000
G1 Z-0.500 F2000
G1 X312.500 F2000
G1 Y-181.800
G1 X0.000F2000
G0 Y-178.600
G1 X312.500 F2000
G1 Y-175.400
G1 X0.000F2000
G0 Y-172.200
G1 X312.500 F2000
G1 Y-169.000
G1 X0.000F2000
G0 Y-165.800
G1 X312.500 F2000
G1 Y-162.600
G1 X0.000F2000
G0 Y-159.400
G1 X312.500 F2000
G1 Y-156.200
G1 X0.000F2000
G0 Y-153.000
G1 X312.500 F2000
G1 Y-149.800
G1 X0.000F2000
G0 Y-146.600
G1 X312.500 F2000
G1 Y-143.400
G1 X0.000F2000
G0 Y-140.200
G1 X312.500 F2000
G1 Y-137.000
G1 X0.000F2000
G0 Y-133.800
G1 X312.500 F2000
G1 Y-130.600
G1 X0.000F2000
G0 Y-127.400
G1 X312.500 F2000
G1 Y-124.200
G1 X0.000F2000
G0 Y-121.000
G1 X312.500 F2000
G1 Y-117.800
G1 X0.000F2000
G0 Y-114.600
G1 X312.500 F2000
G1 Y-111.400
G1 X0.000F2000
G0 Y-108.200
G1 X312.500 F2000
G1 Y-105.000
G1 X0.000F2000
G0 Y-101.800
G1 X312.500 F2000
G1 Y-98.600
G1 X0.000F2000
G0 Y-95.400
G1 X312.500 F2000
G1 Y-92.200
G1 X0.000F2000
G0 Y-89.000
G1 X312.500 F2000
G1 Y-85.800
G1 X0.000F2000
G0 Y-82.600
G1 X312.500 F2000
G1 Y-79.400
G1 X0.000F2000
G0 Y-76.200
G1 X312.500 F2000
G1 Y-73.000
G1 X0.000F2000
G0 Y-69.800
G1 X312.500 F2000
G1 Y-66.600
G1 X0.000F2000
G0 Y-63.400
G1 X312.500 F2000
G1 Y-60.200
G1 X0.000F2000
G0 Y-57.000
G1 X312.500 F2000
G1 Y-53.800
G1 X0.000F2000
G0 Y-50.600
G1 X312.500 F2000
G1 Y-47.400
G1 X0.000F2000
G0 Y-44.200
G1 X312.500 F2000
G1 Y-41.000
G1 X0.000F2000
G0 Y-37.800
G1 X312.500 F2000
G1 Y-34.600
G1 X0.000F2000
G0 Y-31.400
G1 X312.500 F2000
G1 Y-28.200
G1 X0.000F2000
G0 Y-25.000
G1 X312.500 F2000
G1 Y-21.800
G1 X0.000F2000
G0 Y-18.600
G1 X312.500 F2000
G1 Y-15.400
G1 X0.000F2000
G0 Y-12.200
G1 X312.500 F2000
G1 Y-9.000
G1 X0.000F2000
G0 Y-5.800
G1 X312.500 F2000
G1 Y-2.600
G1 X0.000F2000
G0 Y0.600
G1 X312.500 F2000
G1 Y3.800
G1 X0.000F2000
G0 Y7.000
G1 X312.500 F2000
G1 Y10.200
G1 X0.000F2000
G0 Y13.400
G1 X312.500 F2000
G1 Y16.600
G1 X0.000F2000
G0 Y19.800
G1 X312.500 F2000
G1 Y23.000
G1 X0.000F2000
G0 Y26.200
G1 X312.500 F2000
G1 Y29.400
G1 X0.000F2000
G0 Y32.600
G1 X312.500 F2000
G1 Y35.800
G1 X0.000F2000
G0 Y39.000
G1 X312.500 F2000
G1 Y42.200
G1 X0.000F2000
G0 Y45.400
G1 X312.500 F2000
G1 Y48.600
G1 X0.000F2000
G0 Y51.800
G1 X312.500 F2000
G1 Y55.000
G1 X0.000F2000
G0 Y58.200
G1 X312.500 F2000
G1 Y61.400
G1 X0.000F2000
G0 Y64.600
G1 X312.500 F2000
G1 Y67.800
G1 X0.000F2000
G0 Y71.000
G1 X312.500 F2000
G1 Y74.200
G1 X0.000F2000
G0 Y77.400
G1 X312.500 F2000
G1 Y80.600
G1 X0.000F2000
G0 Y83.800
G1 X312.500 F2000
G1 Y87.000
G1 X0.000F2000
G0 Y90.200
G1 X312.500 F2000
G1 Y93.400
G1 X0.000F2000
G0 Y96.600
G1 X312.500 F2000
G1 Y99.800
G1 X0.000F2000
G0 Y103.000
G1 X312.500 F2000
G1 Y106.200
G1 X0.000F2000
G0 Y109.400
G1 X312.500 F2000
G1 Y112.600
G1 X0.000F2000
G0 Y115.800
G1 X312.500 F2000
G1 Y119.000
G1 X0.000F2000
G0 Y122.200
G1 X312.500 F2000
G1 Y125.400
G1 X0.000F2000
G0 Y128.600
G1 X312.500 F2000
G1 Y131.800
G1 X0.000F2000
G0 Y135.000
G1 X312.500 F2000
G1 Y138.200
G1 X0.000F2000
G0 Y141.400
G1 X312.500 F2000
G1 Y144.600
G1 X0.000F2000
G0 Y147.800
G1 X312.500 F2000
G1 Y151.000
G1 X0.000F2000
G0 Y154.200
G1 X312.500 F2000
G1 Y157.400
G1 X0.000F2000
G0 Y160.600
G1 X312.500 F2000
G1 Y163.800
G1 X0.000F2000
G0 Y167.000
G1 X312.500 F2000
G1 Y170.200
G1 X0.000F2000
G0 Y173.400
G1 X312.500 F2000
G1 Y176.600
G1 X0.000F2000
G0 Y179.800
G1 X312.500 F2000
G1 Y183.000
G1 X0.000F2000
G0 Z1.000
M5
G0 X0 Y0

**Comment by neilferreri** [comment]
Oops.  It looks like there is an error in the toolpath when "Both" directions are selected.  I think it should be an easy rework, but I want to test all toolpath options before I push the fix.
Thanks for the catch!

**Comment by ghost** [comment]
You're Welcome, I was'nt sure if this was getting updated, as this seems to be the only bug report. :)

**Comment by neilferreri** [comment]
All should be good now.
