### ISSUE TITLE
Upper right, (here we go again :)

### ISSUE THREAD

**Issue by ghost** [neilferreri/gCode-Generator#2]
Good thing I look before i hit the go button, Its the bit that i have to worry about :)

And Furthermore:
Could you fuzz test your input vars,  I tried negative step-over for a glue job, 
and Firefox seemed to get angry on one of the cores.
(temporarily CPU bound?)
 
I have and invisible ghost called Murphy, Who keeps me on my toes.

Thank you for your Software contribution by the way, Its nice to see Open Source projects like this one give me choice. :) +1: 

PS: Lower right as well:
![Screenshot_2024-02-24_11-22-34](https://github.com/neilferreri/gCode-Generator/assets/101630460/c1bb6466-f1a6-4d84-b2c6-1148df997241)

**Comment by neilferreri** [comment]
Any chance you're using the outdated html?
I just tested again and it all looks good on my end.

I was kinda hoping no one would TRY to break it with negative stepovers. ;)

**Comment by ghost** [comment]
Woops, You're Right, Did a git fetch but Forgot to hard refresh the browser tab.

Closing.

**Comment by ghost** [comment]
I dunno why i used a negative number either, 200% step-over  @ 0.25mm depth 
works fine for gluing waste-boards together.

**Comment by ghost** [comment]
ER, zero point gets selected center in gcode when i choose upper-right, Using cutting-dir both?
The Job starts at lower left?
The job ends @ upper right when i abort?

PS: your code redifines zero when i abort the cnc job, what gcode do you use for home?
milling head ends up at upper right. i will send a movie on what it is doing...

My zero point ( milling head ) has allways started from lower left.
( looks to me like your code is behaving using signed var there,
but my gcode sender is using unsigned. )

I dont think it's me, but i have been known to be wrong before... :)

Am i doing something wrong here?

![Screenshot_2024-02-24_13-09-50](https://github.com/neilferreri/gCode-Generator/assets/101630460/ed2dd8fe-23f4-4942-a365-4c4e98b38314)
![Screenshot_2024-02-24_13-10-36](https://github.com/neilferreri/gCode-Generator/assets/101630460/442d6165-c480-4900-9417-c07300ea7a8d)

**Comment by neilferreri** [comment]
I'm not sure what you mean here.
This is what I get with the same settings you have above. Zero Upper Right.
![image](https://github.com/neilferreri/gCode-Generator/assets/2966894/62dd3c45-3e16-4db9-89b9-a75a65600498)
The path actually starts cutting from the lower left of the defined stock, regardless of where zero is set.

**Comment by ghost** [comment]
Oh , I Misinterpreted and thought that  XY Zero Point meant CUT from upper right, 
Your app simply means "XY Zero Point:" ?, That's why the cnc job looked twice X size 
and wanted to smash into left of machine when job started.

OK, got it.
So, how do i start CUT from upper right and finish at lower left?

**Comment by neilferreri** [comment]
> how do i start CUT from upper right and finish at lower left?

That would require a relatively significant change in the code.  Without thinking on it too much right now, I think I'd have to write separate functions for almost every scenario that way.
Is there a reason you need it to cut from upper right to lower left?

**Comment by ghost** [comment]
Oh, in that case, Its not important, I will run the job normally,Thanks for the speedy reply.
